config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  
  match "/admin" => "admin/site#index", via: [:get], :as => "admin"

  root to: "site#index"
  
  namespace :admin do
    resources :colors, only: [:create]
    resources :vendors, only: [:create]
    resources :materials, only: [:create]
    resources :shapes, only: [:create]
    
    resources :variants, only: [] do
      collection do
        delete 'remove'
      end
    end
    
    resources :products do
      collection do
        get 'generate_variants'
        get 'add_color'
        get 'add_size'
        get 'add_image'
        get 'add_variant'
      end
    end
    
    resources :products_colors, only: [] do
      collection do
        put 'update_mens_sort_order'
        put 'update_womens_sort_order'
        delete 'remove'
      end
    end
    
    resources :product_images, only: [:destroy] do
      collection do
        put 'update_sort_order'
      end
    end
    
    resources :categories
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :vendor
  belongs_to :shape
  belongs_to :material
  belongs_to :category
  
  has_many :products_colors
  has_many :variants, through: :products_colors, dependent: :destroy
  has_many :product_images, through: :products_colors, dependent: :destroy
  
  accepts_nested_attributes_for :products_colors, :reject_if => :incomplete_products_color, :allow_destroy => true
  
  def products_colors_attributes=(attrs)
    if self.new_record?
      super(attrs)
    else
      attrs.each do |_, attributes|
        products_color = ProductsColor.where(color_id: attributes[:color_id], product_id: self.id).first_or_initialize
        products_color.update_attributes(attributes)
      end
    end
  end
  
  # has_many :variants, -> { order(size: :desc) }, after_remove: :reset_featured_colors!
  # has_many :product_images, -> { order(sort_order: :asc) }

  
  # validates_associated :variants
  # validate :variants_have_different_sizes_and_colors
  
  
  # def featurable_mens_colors
  #   self.mens_variants.where(active: true).map(&:color).compact.uniq
  # end
  # 
  # def featurable_womens_colors
  #   self.womens_variants.where(active: true).map(&:color).compact.uniq
  # end
  # 
  # def mens_variants
  #   self.variants.where(men: true)
  # end
  # 
  # def womens_variants
  #   self.variants.where(women: true)
  # end
  # 
  # def reset_featured_colors!(variant)
  #   return if variant.new_record?
  #   color = variant.color
  #   # if self.variants.where(color_id: color.id).empty?
  #   #   if self.featured_mens_color == color
  #   #     self.featured_mens_color = self.variants.first.color
  #   #     self.save
  #   #   end
  #   #   if self.featured_womens_color == color
  #   #     self.featured_womens_color = self.variants.first.color
  #   #     self.save
  #   #   end
  #   # end
  # end
  # 
  # def variants_have_different_sizes_and_colors
  #   existing_combinations = []
  #   self.variants.each do |variant|
  #     size_and_color_combination = [variant.size, variant.color]
  #     if !existing_combinations.include?(size_and_color_combination)
  #       existing_combinations << size_and_color_combination
  #     else
  #       self.errors.add(:base, "Variants can't have identical size and color")
  #     end
  #   end
  # end
  
  private
  
    def incomplete_products_color(attributed)
      attributed.keys == ["_destroy", "variants_attributes"] || attributed.keys == ["_destroy"]
    end
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  
  def index
    @products = Product.all
  end
  
  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to edit_admin_product_path(@product), notice: "Your product was successfully updated."
    else
      render 'edit'
    end
  end
  
  def new
    @product = Product.new
    @product.variants.build
  end
  
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to edit_admin_product_path(@product), notice: "Your product was successfully created."
    else
      render 'new'
    end
  end
  
  def generate_variants
    price = params[:price] || 0
    sizes_and_measurements = params[:sizes_and_measurements]
    sizes_and_weights = params[:sizes_and_weights]
    colors_and_genders = params[:colors_and_genders]
    @products_colors = []
    colors_and_genders.each do |color_id, gender|
      product_color = ProductsColor.new(color_id: color_id,
                                        mens: gender.include?("men"),
                                        womens: gender.include?("women")
                                        )
      sizes_and_measurements.each do |size_id, measurements|
        product_color.variants << Variant.new(size_id: size_id,
                                          measurements: measurements,
                                          weight: sizes_and_weights[size_id],
                                          price: price)
      end
      @products_colors << product_color
    end

    respond_to do |format|
      format.js
    end
  end
  
  def add_size
    respond_to do |format|
      format.js
    end
  end
  
  def add_color
    respond_to do |format|
      format.js
    end
  end
  
  
  def add_variant
    @product = Product.find(params[:product_id])
    respond_to do |format|
      format.js
    end
  end
  
  private
  
    def product_params
      params.require(:product).permit(:name, 
                                      :short_description, 
                                      :long_description, 
                                      :active, 
                                      :meta_description, 
                                      :page_title,
                                      :taxable, 
                                      :vendor_id, 
                                      :material_id, 
                                      :shape_id,
                                      :category_id, 
                                      :products_colors_attributes => [
                                        :id, 
                                        :mens, 
                                        :womens,
                                        :color_id,
                                        :_destroy, 
                                        :product_images_attributes => [
                                          :color_id, 
                                          :image => []
                                        ],
                                        :variants_attributes => [
                                          :id,
                                          :weight,
                                          :measurements,
                                          :sku,
                                          :price,
                                          :in_stock,
                                          :products_color_id,
                                          :size_id
                                        ]                                        
                                      ]
                                      )
    end
    
end

app/views/admin/products/_color.html.erb
<div class="color_inputs">
<%= label_tag "Color" %>
<%= select_tag :color, color_options_with_extra_link_to_create_color, class: "colors" %>
<%= check_box_tag "gender[]", "men", true, id: nil, class: "genders" %> Men
<%= check_box_tag "gender[]", "women", true, class: "genders" %> Women
</div>

app/views/admin/products/_products_color.html.erb
<div class="color_container products_color_number_<%= pc.index %>">
	<h3>
	
	<% if pc.object.new_record? %>
		<!-- <%= pc.collection_select :color_id, Color.all, :id, :name %> -->
		<div class="colors_container">
			<%= pc.select :color_id, color_options_with_extra_link_to_create_color, {}, {class: "colors"} %>
		</div>
	<% else %>
		<%= pc.object.color.name %>
		<%= pc.hidden_field :color_id %>
	<% end %>
	<%= link_to "Delete", remove_admin_products_colors_path(id: pc.object.id, index: pc.index), remote: true, method: :delete %>
	</h3>
	
	
	<%= pc.label "product_images_attributes[image]", "Add Images" %>
	<%= pc.file_field "product_images_attributes[image]", multiple: true %>


	<ul class="sorted_product_image_list">
	<% pc.object.product_images.each do |product_image| %>
		<li id="<%= product_image.id %>">
			<%= image_tag(product_image.image.url(:thumb)) %>
			<%= link_to image_tag("delete.png", width: 20), admin_product_image_path(product_image), method: :delete, remote: true %>
		</li>
	<% end %>
	</ul>
	<%= pc.check_box :mens %> <%= pc.label :mens, "Men's" %>
	<%= pc.check_box :womens %>  <%= pc.label :womens, "Women's" %><br>
	
	<% pc.object.variants.build if pc.object.new_record? %>
	<%= pc.fields_for :variants do |v| %>
		<div class="variant_container variant_number_<%= v.index %>">
			
			<% if v.object.new_record? %>
				<%= v.collection_select :size_id, Size.all, :id, :name, {}, {class: "size_select"} %>
			<% else %>
				<%= v.object.size.name %>
				<%= v.hidden_field :size_id %>
			<% end %>
			<%= link_to "Delete", remove_admin_variants_path(id: v.object.id, index: v.index), remote: true, method: :delete %><br>
			
			<%= v.label :in_stock, "In stock" %>
			<%= v.check_box :in_stock %><br>
			<%= v.label :price %>
			<%= v.text_field :price, class: "variant_price" %><br>
			<%= v.label :measurements %>
			<%= v.text_field :measurements %><br>
			<%= v.label :sku %>
			<%= v.text_field :sku %><br>
			<%= v.label :weight %>
			<%= v.text_field :weight %><br>
		</div>
	<% end %>
</div>

app/views/admin/products/_size.html.erb
<div class="size_inputs">
<%= label_tag "Size" %>
<%= select_tag :size, options_from_collection_for_select(Size.all, :id, :name), id: nil, class: "sizes" %>
<%= label_tag "Measurements" %>
<%= text_field_tag :measurements, nil, id: nil, class: "measurements" %>
<%= label_tag "Weight (LBS)" %>
<%= text_field_tag :weight, "0.25", id: nil, class: "weight" %>
</div>

app/views/admin/products/_variant_combinations.html.erb
  <table class="variants_table">
    <thead>
			<th>Color</th>
      <th>Section</th>
			<th>Size</th>
      <th>Price</th>
      <th>Measurements</th>
      <th>SKU</th>
      <th>Weight</th>
    </thead>

		<% products_colors.each_with_index do |products_color, pc_index| %>
		<tr>
			<td><%= products_color.color.name %></td>
			<td>
				<%= check_box_tag "product[products_colors_attributes][#{pc_index}][mens]", 1, products_color.mens? %> Men's
				<%= check_box_tag "product[products_colors_attributes][#{pc_index}][womens]", 1, products_color.womens? %> Women's
			</td>
			<%= hidden_field_tag "product[products_colors_attributes][#{pc_index}][color_id]", products_color.color_id %>
		
			
			<% products_color.variants.each_with_index do |variant, v_index| %>
				<% if v_index == 0 %>
						<td>
							<%= select_tag "product[products_colors_attributes][#{pc_index}][variants_attributes][#{v_index}][size_id]", options_from_collection_for_select(Size.all, :id, :name, variant.size_id) %>
						</td>
						<td>
							<%= text_field_tag "product[products_colors_attributes][#{pc_index}][variants_attributes][#{v_index}][price]", variant.price %>
						</td>
						<td>
							<%= text_field_tag "product[products_colors_attributes][#{pc_index}][variants_attributes][#{v_index}][measurements]", variant.measurements %>
						</td>
						<td>
							<%= text_field_tag "product[products_colors_attributes][#{pc_index}][variants_attributes][#{v_index}][sku]", variant.sku %>
						</td>
						<td>
							<%= text_field_tag "product[products_colors_attributes][#{pc_index}][variants_attributes][#{v_index}][weight]", variant.weight %>
						</td>
					</tr>
				<% else %>
				<tr>
					<td></td>
					<td></td>
					<td>
						<%= select_tag "product[products_colors_attributes][#{pc_index}][variants_attributes][#{v_index}][size_id]", options_from_collection_for_select(Size.all, :id, :name, variant.size_id) %>
					</td>
					<td>
						<%= text_field_tag "product[products_colors_attributes][#{pc_index}][variants_attributes][#{v_index}][price]", variant.price %>
					</td>
					<td>
						<%= text_field_tag "product[products_colors_attributes][#{pc_index}][variants_attributes][#{v_index}][measurements]", variant.measurements %>
					</td>
					<td>
						<%= text_field_tag "product[products_colors_attributes][#{pc_index}][variants_attributes][#{v_index}][sku]", variant.sku %>
					</td>
					<td>
						<%= text_field_tag "product[products_colors_attributes][#{pc_index}][variants_attributes][#{v_index}][weight]", variant.weight %>
					</td>
				</tr>
				<% end %>

			<% end %>
		</tr>
    <% end %>
  </table>

app/views/admin/products/add_color.js.erb
$(".colors_container").append("<%=j render 'color' %>");

app/views/admin/products/add_size.js.erb
$(".sizes_container").append("<%=j render 'size' %>");

app/views/admin/products/edit.html.erb
<h1>Edit product</h1>


<%= nested_form_for [:admin, @product], multipart: true do |form| %>

	<% if @product.errors.any? %>
	<ul>
	  <% @product.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>
	</ul>
	<% end %>
	<div class="field">
		<%= form.label :name %>
		<%= form.text_field :name %>
	</div>
	<div class="field">
		<%= form.label :short_description %>
		<%= form.text_area :short_description %>
	</div>
	<div class="field">
		<%= form.label :long_description %>
		<%= form.text_area :long_description %>
	</div>
	
	<div class="field">
		<%= form.label :category_id, "Category" %>
		<%= form.collection_select :category_id, Category.all, :id, :name %>
	</div>
	
	<div class="field vendor_container">
		<%= form.label :vendor_id, "Vendor" %>
		<%= form.select :vendor_id, vendor_options_with_extra_link_to_create_vendor(form.object.vendor_id) %>
	</div>
	
	<div class="field material_container">
		<%= form.label :material_id, "Material" %>
		<%= form.select :material_id, material_options_with_extra_link_to_create_material(form.object.material_id) %>
	</div>
	
	<div class="field shape_container">
		<%= form.label :shape_id, "Shape" %>
		<%= form.select :shape_id, shape_options_with_extra_link_to_create_shape(form.object.shape_id) %>
	</div>
	
	<div class="field">
		<%= form.label :taxable %>
		<%= form.check_box :taxable %>
	</div>
	
	
	<h3>Master Price Adjuster</h3>
	<%= text_field_tag "master_price", nil, id: "master_price" %>
	
	<%= form.fields_for :products_colors do |pc| %>
		<%= render 'products_color.html.erb', :pc => pc %>
		
		<%= pc.link_to_add "Add Variant", :variants %>
	<% end %>
	
	
	<div>
		<%= form.link_to_add "Add Color", :products_colors %>
	</div>
	<h3>Men's Color Order</h3>
	<ul class="sorted_product_mens_color_list">
		<% form.object.products_colors.order('mens_sort_order ASC').each do |products_color| %>
			<li id="<%= products_color.id %>">
				<%= products_color.color.name %>
			</li>
		<% end %>
	</ul>
	
	<h3>Women's Color Order</h3>
	<ul class="sorted_product_womens_color_list">
		<% form.object.products_colors.order('womens_sort_order ASC').each do |products_color| %>
			<li id="<%= products_color.id %>">
				<%= products_color.color.name %>
			</li>
		<% end %>
	</ul>

	<div class="field">
		<%= form.label :page_title %>
		<%= form.text_field :page_title %>
	</div>
	<div class="field">
		<%= form.label :meta_description %>
		<%= form.text_area :meta_description %>
	</div>
	
	
	<div class="field">
		<label class="radio">
			<%= form.radio_button :active, true, checked: form.object.active? %>
			Active
		</label>
		<label class="radio">
			<%= form.radio_button :active, false, checked: !form.object.active? %>
			Inactive
		</label>
	</div>
	
	<%= form.submit %>
	
<% end %>

app/views/admin/products/generate_variants.js.erb
$(".variant_container").html("<%= j render :partial => "variant_combinations", locals: {:products_colors => @products_colors} %>");

app/views/admin/products/index.html.erb
<div>
	<%= link_to "New product", new_admin_product_path %>
</div>
<% @products.each_with_index do |product, index| %>
	<%= index+1 %>. <%= link_to product.name, edit_admin_product_path(product) %><br>
<% end %>

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= form_for [:admin, @product] do |form| %>
	<div class="field">
		<%= form.label :name %>
		<%= form.text_field :name %>
	</div>
	<div class="field">
		<%= form.label :short_description %>
		<%= form.text_area :short_description %>
	</div>
	<div class="field">
		<%= form.label :long_description %>
		<%= form.text_area :long_description %>
	</div>
	
	<div class="field">
		<%= form.label :category_id, "Category" %>
		<%= form.collection_select :category_id, Category.all, :id, :name %>
	</div>
	
	<div class="field vendor_container">
		<%= form.label :vendor_id, "Vendor" %>
		<%= form.select :vendor_id, vendor_options_with_extra_link_to_create_vendor(form.object.vendor_id) %>
	</div>
	
	<div class="field material_container">
		<%= form.object.material_id%>
		<%= form.label :material_id, "Material" %>
		<%= form.select :material_id, material_options_with_extra_link_to_create_material(form.object.material_id) %>
	</div>
	
	<div class="field shape_container">
		<%= form.label :shape_id, "Shape" %>
		<%= form.select :shape_id, shape_options_with_extra_link_to_create_shape(form.object.shape_id) %>
	</div>
	
	<div class="field">
		<%= form.label :taxable %>
		<%= form.check_box :taxable, checked: true %>
	</div>
	
	<h3>Variant Generator</h3>
	<div class="field">
		<%= label_tag :price %>
		<%= text_field_tag :price, "0.00" %>
	</div>
	
	<div class="sizes_container">
		<%= render "size" %>
	</div>
	
	<%= link_to "Add Size", add_size_admin_products_path, remote: true %>
	<div class="colors_container">
		<%= render :partial => "color" %>
	</div>
	<span class="add_color"><%= link_to "Add Color", add_color_admin_products_path, remote: true %></span><br>
	
	
	<%= link_to "Generate", generate_variants_admin_products_path, id: "generate_variants_link"  %><br>
	
	<div class="variant_container"></div>
	
	<div class="field">
		<%= form.label :page_title %>
		<%= form.text_field :page_title %>
	</div>
	<div class="field">
		<%= form.label :meta_description %>
		<%= form.text_area :meta_description %>
	</div>

	
	<%= form.submit %>
	
<% end %>