config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  
  match "/admin" => "admin/site#index", via: [:get], :as => "admin"

  root to: "site#index"
  
  namespace :admin do
    resources :colors, only: [:create]
    resources :vendors, only: [:create]
    resources :materials, only: [:create]
    resources :shapes, only: [:create]
    
    resources :variants, only: [] do
      collection do
        delete 'remove'
      end
    end
    
    resources :products do
      collection do
        get 'generate_variants'
        get 'add_color'
        get 'add_size'
        get 'add_image'
        get 'add_variant'
      end
    end
    
    resources :products_colors, only: [] do
      collection do
        put 'update_mens_sort_order'
        put 'update_womens_sort_order'
        delete 'remove'
      end
    end
    
    resources :product_images, only: [:destroy] do
      collection do
        put 'update_sort_order'
      end
    end
    
    resources :categories
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ilook</title>
  <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'admin', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if current_user %>
		<%= link_to "Dashboard", admin_path %>
		<%= link_to "Log out", destroy_user_session_path, method: :delete %>
	<% else %>
		<%= link_to "Log in", new_user_session_path %>
	<% end %>
	
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ilook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if current_user %>
		<%= link_to "Dashboard", admin_path %>
		<%= link_to "Log out", destroy_user_session_path, method: :delete %>
	<% else %>
		<%= link_to "Log in", new_user_session_path %>
	<% end %>
	
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>